#!/usr/bin/env bash
# Configure your domain zone so that the subdomain

print_info () {
    subdomain=$1
    domain=$2
    record=$(dig $subdomain.$domain +short)
    record_type=$(dig $subdomain.$domain +short | awk '{print $1}')
    echo "The subdomain $subdomain is a $record_type record and points to $record"
}

if [ "$#" -eq 2 ]
then
    print_info $2 $1
else
    domains=("www" "lb-01" "web-01" "web-02")
    for subdomain in ${domains[@]}; do
        print_info $subdomain $1
    done
fi