#!/usr/bin/env bash
# Check if all required arguments are provided
if [ $# -ne 4 ]; then
  newArg=${0#??}
  echo "Usage: $newArg PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign input arguments to variables
pth=$1
ipd=$2
usrn=$3
keyPth=$4

# Check if the file exists
if [ ! -f $pth ]; then
  echo "Error: $pth not found"
  exit 1
fi

# Transfer the file to the server
scp -o StrictHostKeyChecking=no -i $keyPth $pth $usrn@$ipd:~
