#!/usr/bin/env bash
# Check if all required arguments are provided
if [ $# -ne 4 ]; then
  newArg=${0#??}
  echo "Usage: $newArg PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign input arguments to variables
local_file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Check if the file exists
if [ ! -f $local_file_path ]; then
  echo "Error: $local_file_path not found"
  exit 1
fi

# Transfer the file to the server
scp -o StrictHostKeyChecking=no -i $ssh_key_path $local_file_path $username@$server_ip:~

# echo "File transferred successfully to $username@$server_ip:~/"
