#!/usr/bin/env bash
# Update package index and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure Nginx to listen on port 80
sudo sed -i 's/# listen 80/listen 80/' /etc/nginx/sites-available/default

# Restart Nginx
sudo /etc/init.d/nginx restart

# Create HTML file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html
