#!/usr/bin/env bash
# Script that configures a new Ubuntu machine  requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
new_string="server_name _;\n\
\trewrite ^\/redirect_me \
https:\/\/github.com\/waley-code permanent;"
sudo sed -i "s/server_name _;/$new_string/" \
    /etc/nginx/sites-enabled/default
sudo service nginx restart

