#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# updates machine
# Install and configure HAproxy on your lb-01 server
# updates machine                                                      et-tools amd64 1.60+git20180626.aebd88e-1ubuntu1 [196 kB]
sudo apt-get update
# Installs Haproxy
sudo apt-get install haproxy -y                                        Preparing to unpack .../net-tools_1.60+git20180626.aebd88e-1ubuntu1_amd64.deb ...
# Activate haproxy in config
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
# configure HAproxy on your lb-01 server
sudo sed -i "$ a\listen 33776-lb-01\n\tbind *:80\n\tmode http\n\tbalancTEN      48923/haproxye roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 33776-web-01 54.174.243.255:80 check\n\tserver 33776-web-02 54.208.245.251:80 
check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
sudo service haproxy restart
