#!/usr/bin/env bash
# a Bash script that:

echo $$ > "/var/run/myscript.pid"
trap "echo 'I hate the kill command' ; exit" SIGTERM
trap "echo 'Y U no love me?'" SIGINT
trap "rm '/var/run/myscript.pid'; exit" SIGQUIT SIGTERM
while ((1));
do
    echo "To infinity and beyond"
    sleep 2
done
