#!/usr/bin/env bash
a Bash script that:

script_pid=$$
echo $script_pid > /var/run/myscript.pid
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?'" SIGINT
trap "rm -rf /var/run/myscript.pid ; exit" SIGQUIT
while ((1));
do
    echo "To infinity and beyond"
done
