#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
j=0
for i in {0..10}
do
    if [ "$i" == 9 ]; then
        echo "Hi"
    else
        echo "Best School"
    j=$((j+1))
    fi
done
j=0