#!/usr/bin/env bash
# This script is displaying "Best School" 8 times & bad luck or good luck

j=1
while [ $j -le 10 ]
do
    if [ "$j" == 4 ]; then
        echo "bad luck"
    elif [ "$j" == 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
j=$((j+1))
done
j=0