#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 and

j=1
while [ $j -le 20 ]
do
    echo $j
    case "$j" in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
        ;;
    esac
    j=$((j+1))
done
j=0