#!/usr/bin/env bash
# a Bash script that gives you information about the school file.

file_search="school"
if [ -e "$file_search" ]
then
    echo "school file exists"

    if [ -f "$file_search" ]
    then
        if [ -s "$file_search" ]
        then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
        echo "school is a regular file"
    fi
    if [ -d "$file_search" ]
    then
        echo "school file is not empty"
    fi
else
    echo "school file does not exist"
fi