#!/usr/bin/env bash
#  a Bash script that configures an Ubuntu serveir
cp /etc/hosts ~/hosts.old
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.old
echo "8.8.8.8 facebook.com" >> ~/hosts.old
cp -f ~/hosts.old /etc/hosts
