#!/usr/bin/env bash
# an SSH configuration file for SSH client
Host *
    Hostname 54.174.243.255
    User ubuntu
    IdentityFile ~/.ssh/id_rsa
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
